# Change these first
owner: phieri # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

NOTIFICATION_CUSTOM_WEBHOOK: false
NOTIFICATION_CUSTOM_WEBHOOK_URL: https://api.pushover.net/1/messages.json

sites:
  - name: Webbplats
    url: https://www.ssa.se
    method: HEAD
  - name: Certifikatprov
    url: https://examen.ssa.se
    method: HEAD
  - name: Utbildning
    url: https://kurs.ssa.se
    method: HEAD
  - name: Forum
    url: https://forum.ssa.se
    method: HEAD
  - name: Contest
    url: https://contest.ssa.se
    method: HEAD
  - name: SAC
    url: https://www.sactest.net
    method: HEAD
  - name: Kansli
    url: https://kansli.ssa.se
    method: HEAD
  - name: Hamshop
    url: https://hamshop.ssa.se
    method: HEAD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ssa.se
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptid SSA
  introTitle: ""
  introMessage: "Detta är en statussida som visar realtidsdata för SSA:s webbplattformar."
  navbar:
    - title: Status
      href: /
    - title: ssa.se
      href: https://www.ssa.se
  metaTags:
    - name: "color-scheme"
      content: "dark light"

i18n:
  locale: sv-SE
  allSystemsOperational: Alla system fungerar
  averageResponseTime: "Genomsnittlig svarstid: $TIME ms"
  up: Uppe
  down: Nere
  degraded: "Försämrad"
  incidentFixed: Fixat
  incidentOngoing: Pågående
  incidentOpenedAt: Öppnades klockan
  incidentClosedAt: Stängdes klockan
  overallUptimeTitle: Total upptid
  overallUptime: "Total upptid: $UPTIME"
  duration1Y: "1å"
  durationAll: allt
  durationMin: "$DURATION minuter"
  errorTitle: "Ett fel inträffade"
  startedAt: Startade klockan
  startsAt: Startar klockan
  duration: Längd
  liveStatus: Live-status
  scheduledMaintenance: Planerat underhåll
  responseTimeMs: "Svarstid (ms)"
  footer: "Denna sida har [öppen källkod]($REPO) och drivs med [Upptime](https://upptime.js.org)."
