# Change these first
owner: phieri # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Webbplats
    url: https://www.ssa.se
    method: HEAD
  - name: Certifikatprov
    url: https://examen.ssa.se
    method: HEAD
  - name: Utbildning
    url: https://kurs.ssa.se
    method: HEAD
  - name: Forum
    url: https://forum.ssa.se
    method: HEAD
  - name: Contest
    url: https://contest.ssa.se
    method: HEAD
  - name: Kansli
    url: https://kansli.ssa.se
    method: HEAD
  - name: Hamshop
    url: https://hamshop.ssa.se
    method: HEAD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptid SSA
  introTitle: ""
  introMessage: "Detta är en statussida som visar realtidsdata via GitHub."
  navbar:
    - title: Status
      href: /
    - title: ssa.se
      href: https://www.ssa.se
  metaTags:
    - name: "color-scheme"
      content: "dark light"

i18n:
  locale: sv-SE
  averageResponseTime: "Genomsnittlig svarstid: $TIME ms"
  up: Uppe
  down: Nere
  overallUptimeTitle: Total upptid
  duration1Y: "1å"
  durationAll: allt
  durationMin: "$DURATION minuter"
  responseTimeMs: "Svarstid (ms)"
  footer: "Denna sida har [öppen källkod]($REPO) och drivs med [Upptime](https://upptime.js.org)."
