owner: phieri # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: phieri

sites:
  - name: Webbplats
    url: https://www.ssa.se
    method: HEAD
  - name: Certifikatprov
    url: https://examen.ssa.se
    method: HEAD
  - name: Utbildning
    url: https://kurs.ssa.se
    method: HEAD
  - name: Forum
    url: https://forum.ssa.se
    method: HEAD
  - name: Contest
    url: https://contest.ssa.se
    method: HEAD
  - name: HF Contest Cup
    url: https://hfcup.ssa.se
    method: HEAD
  - name: SAC
    url: https://www.sactest.net
    method: HEAD
  - name: Kansli
    url: https://kansli.ssa.se
    method: HEAD
  - name: Hamshop
    url: https://hamshop.ssa.se
    method: HEAD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.ssa.se
  baseUrl: /upptime
  logoUrl: https://www.ssa.se/wp-content/themes/finewp-ssa/img/ssa-logga.png
  name: Driftstatus
  introTitle: ""
  introMessage: "Här visas tillgänglighetsdata för SSA:s webbplattformar."
  navbar:
    - title: ssa.se
      href: https://www.ssa.se
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "format-detection"
      content: "telephone=no"

# List of available strings at https://github.com/upptime/status-page/blob/master/i18n.yml
#       and at https://github.com/orgs/upptime/discussions/161#discussioncomment-256389
i18n:
  activeIncidents: Pågående incidenter
  allSystemsOperational: Alla system fungerar
  activeIncidentSummary: Öppnades $DATE och har $POSTS inlägg
  averageResponseTime: "Genomsnittlig svarstid: $TIME ms"
  duration: Längd
  durationMin: $DURATION minuter
  duration1Y: 1å
  durationAll: allt
  errorHome: Gå till startsidan
  errorTitle: Ett fel inträffade
  errorText: Du kan försöka igen om en liten stund.
  history: Historik
  incidentReport: "Incidentrapport nr $NUMBER →"
  incidentFixed: Åtgärdad
  incidentOngoing: Pågående
  incidentOpenedAt: Öppnades klockan
  incidentClosedAt: Stängdes klockan
  incidentViewOnGitHub: Visa och följ på GitHub
  liveStatus: Live-status
  overallUptimeTitle: Total tillgänglighet
  overallUptime: "Total tillgänglighet: $UPTIME"
  startedAt: Startade klockan
  startsAt: Startar klockan
  scheduledMaintenance: Planerat underhåll
  responseTime: Svarstid
  responseTimeMs: Svarstid (ms)
  uptime: Tillgänglighet
  up: Uppe
  down: Nere
  degraded: Försämrad
  loading: Laddar
  footer: "Denna sida har [öppen källkod]($REPO) och drivs med [Upptime](https://upptime.js.org)."
  locale: sv-SE
