# Change these first
owner: phieri # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Webbplats
    url: https://www.ssa.se
    method: HEAD
  - name: Certifikatprov
    url: https://examen.ssa.se
    method: HEAD
  - name: Utbildning
    url: https://kurs.ssa.se
    method: HEAD
  - name: Kansli
    url: https://kansli.ssa.se
    method: HEAD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: "This is a status page which uses **real-time** data via GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
i18n:
  locale: sv-SE
  duration1Y: 1å
  responseTimeMs: Svarstid (ms)
